Development
deshpandeshriram/genkwiz pull request #15
Opened 2021-06-16 17:07 UTC by vrushbru

Code refactor

2021-07-05 17:32 UTC, rdsarda commented on api-spec.yaml
> +                        description: Id of the quiz generated.
Typo -- its the id of the session

2021-07-05 17:33 UTC, rdsarda commented on api-spec.yaml
> +          description: Bad Request
extra space character at the end, can be removed

2021-07-05 17:35 UTC, rdsarda commented on api-spec.yaml
> +                  userTime:
please provide description. What is the unit of the time here?

2021-07-05 17:37 UTC, rdsarda commented on api-spec.yaml
> +             type: object
Instead of inline definition of this request object, can we create a type and refer that here?

2021-07-05 17:38 UTC, rdsarda commented on api-spec.yaml
> +                 $ref : '#/components/schemas/QuizStatus'
unwanted extra space characters

2021-07-05 17:38 UTC, rdsarda commented on api-spec.yaml
> +                 $ref: '#/components/schemas/Performance'
extra space in indentation

2021-07-05 17:39 UTC, rdsarda commented on api-spec.yaml
> +          example: 'f615d834-d8fd-11eb-b8bc-0242ac130003'
are avatarIds uuids?

2021-07-05 17:41 UTC, rdsarda commented on api-spec.yaml
> +        id:
what's the purpose of the id for an Hint?

2021-07-05 17:51 UTC, rdsarda commented on api-spec.yaml
> +      name: sessionId
Please rename it to `x-genkwiz-session-id`

2021-07-05 17:51 UTC, rdsarda commented on api-spec.yaml
> +    Mode:
What is the purpose of this object?

2021-07-05 18:10 UTC, rdsarda commented on api-spec.yaml
> +        - SKIPPED
Please name the enums in all small case letters.

2021-07-05 18:11 UTC, rdsarda commented on api-spec.yaml
> +        maxSore:
typo - maxScore

2021-07-05 18:12 UTC, rdsarda commented on api-spec.yaml
> +      title: Question status
Please rename the `title` to `Question State`.

2021-07-05 18:14 UTC, rdsarda commented on api-spec.yaml
> +        maxTime:
Is this timestamp or the amount of maximum time allowed to solve the question?

2021-07-08 03:24 UTC, rdsarda requested changes

2021-07-08 03:24 UTC, rdsarda commented on DB_Script.sql
>  question_id int not null,
What is the purpose of `question_id` here?

2021-07-08 03:24 UTC, rdsarda commented on api-spec.yaml
> +    Mode:
What is the purpose of this object? I see that there is description, but how do we plan to use this?

2021-07-08 03:24 UTC, rdsarda commented on api-spec.yaml
> +          description: 'Time take by the user to answer this question in seconds.'
typo `take` --> `taken`

2021-07-08 03:24 UTC, rdsarda commented on api-spec.yaml
> +              description: 'Time take by the user to answer this question in seconds'
typo `take` --> `taken`

2021-07-08 16:36 UTC, nagnath-sawant commented on DB_Script.sql
>  question_id int not null,
As, multimedia is associated with question, we can keep this info for reference.

2021-07-08 16:38 UTC, nagnath-sawant commented on api-spec.yaml
> +    Mode:
This is part of Question response, not sure about the earlier thoughts but few fields like Max Time and Max score can be utilized while displaying question.

2021-07-10 16:24 UTC, nagnath-sawant commented on DB_Script.sql
>  question_id int not null,
Removed it.

2021-07-10 16:24 UTC, nagnath-sawant commented on api-spec.yaml
> +              description: 'Time take by the user to answer this question in seconds'
done

2021-07-10 16:24 UTC, nagnath-sawant commented on api-spec.yaml
> +          description: 'Time take by the user to answer this question in seconds.'
done

2021-07-10 16:30 UTC, nagnath-sawant commented on api-spec.yaml
> +        id:
Used in question response to get more details about quiz mode

2021-07-10 17:59 UTC, rdsarda approved these changes

2021-07-10 17:59 UTC, merged